In [1]:
from fraud import collectAllFeaturesBaseline, collectAllFeaturesBaselineTest
from fraud import calculate_mutual_information, visualize_mutual_information, addCombinations
from fraudfeaturefinder import fraudfeaturefinder, apply_saved_combinations

In [2]:
df_features = collectAllFeaturesBaseline(without_t_features=True)
df_features

/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraud.py:35: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  self._frames[str(p)] = pd.read_csv(p)

           client_id  target  disrict  region  client_catg
0     train_Client_0     0.0       60     101           11
1     train_Client_1     0.0       69     107           11
2    train_Client_10     0.0       62     301           11
3   train_Client_100     0.0       69     105           11
4  train_Client_1000     0.0       62     303           11

/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraud.py:529: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  merge_df['creation_date'] = pd.to_datetime(merge_df['creation_date'])

,client_id,target,disrict,region,client_catg,f_invoive_date_diff_days,f_invoive_date_median_months,f_invoive_date_median_years,f_counter_statue_error_occured,f_counter_regions,...,tarif_type,f_index_cons_error_sum,f_counter_statue_mean,f_client_tenure_days,f_counter_number_nunique,f_tarif_change_count,avg_consumption_per_month,remarque_frequency,avg_remarque_length,faulty_status_rate
0,train_Client_0,0.0,60,101,11,120.5,3.958607,0.329911,0,0,...,11,0,0.000000,8844,1,1,78.419753,1.0,1.0,0.0
1,train_Client_1,0.0,69,107,11,121.5,3.991459,0.332649,0,0,...,11,0,0.000000,6152,1,1,128.931250,1.0,1.0,0.0
2,train_Client_10,0.0,62,301,11,147.0,4.829172,0.402464,0,0,...,11,0,0.000000,12103,1,1,129.801724,1.0,1.0,0.0
3,train_Client_100,0.0,69,105,11,121.0,3.975033,0.331280,0,0,...,11,0,0.000000,5920,1,1,0.285714,1.0,1.0,0.0
4,train_Client_1000,0.0,62,303,11,124.0,4.073587,0.339493,0,0,...,11,0,0.000000,1707,1,1,248.403846,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135488,train_Client_99995,0.0,62,304,11,113.0,3.712221,0.309377,1,0,...,11,-139,0.070423,5448,3,2,0.463333,1.0,1.0,0.0
135489,train_Client_99996,0.0,63,311,11,0.0,0.000000,0.000000,1,0,...,40,0,0.268293,2427,3,2,47.818750,1.0,1.0,0.0
135490,train_Client_99997,0.0,63,311,11,26.0,0.854139,0.071184,0,0,...,11,0,0.000000,2906,2,2,66.425676,1.0,1.0,0.0
135491,train_Client_99998,0.0,60,101,11,122.0,4.007884,0.334018,0,0,...,10,0,0.000000,4380,1,1,61.750000,1.0,1.0,0.0
135492,train_Client_99999,0.0,60,101,11,122.0,4.007884,0.334018,0,0,...,11,0,0.000000,3872,1,1,114.833333,1.0,1.0,0.0

In [3]:
df_features_mutual = calculate_mutual_information(df_features, target_col="target", exclude_cols=["client_id", "target"])
df_features_mutual.head(100)

                                       Feature  MI_Score
0                                  client_catg  0.030512
1                           remarque_frequency  0.029614
2                     f_counter_number_nunique  0.027498
3                          avg_remarque_length  0.019181
4                                   tarif_type  0.017522
5                         f_tarif_change_count  0.013646
6                      f_total_consumption_max  0.010871
7                         f_client_tenure_days  0.010476
8               f_counter_statue_error_occured  0.009878
9                             f_index_diff_max  0.009655
10                     f_total_consumption_std  0.009533
11                            f_index_diff_std  0.009412
12                                     disrict  0.009124
13                    consommation_level_2_max  0.008809
14                   consommation_level_3_mean  0.008709
15  f_region_std_deviation_consumption_level_2  0.008677
16                    consommation_level_1_max  0.007770
17                   consommation_level_2_mean  0.007490
18  f_region_std_deviation_consumption_level_3  0.007479
19                    consommation_level_2_std  0.007151
20                    consommation_level_3_std  0.007132
21                    consommation_level_1_std  0.007045
22                    consommation_level_3_max  0.006988
23                    consommation_level_4_max  0.006690
24  f_region_std_deviation_consumption_level_4  0.006596
25  f_region_std_deviation_consumption_level_1  0.006120
26                    f_total_consumption_mean  0.005970
27                    consommation_level_4_std  0.005866
28       f_region_median_billing_frequence_per  0.005833
29                   avg_consumption_per_month  0.005652
30                           f_index_diff_mean  0.005446
31                   consommation_level_4_mean  0.005414
32                                      region  0.004869
33                   consommation_level_1_mean  0.004717
34                    consommation_level_1_min  0.004123
35                       f_counter_statue_mean  0.003689
36                     f_total_consumption_min  0.003519
37                            f_index_diff_min  0.003298
38                    f_invoive_date_diff_days  0.002818
39                f_invoive_date_median_months  0.002379
40                 f_invoive_date_median_years  0.001777
41                      f_index_cons_error_sum  0.000767
42                    consommation_level_4_min  0.000121
43                    consommation_level_2_min  0.000062
44                    consommation_level_3_min  0.000000
45                           f_counter_regions  0.000000
46                          faulty_status_rate  0.000000

In [5]:
top_n_features = df_features_mutual.head(20)["Feature"].tolist()
print(top_n_features)

['client_catg', 'remarque_frequency', 'f_counter_number_nunique', 'avg_remarque_length', 'tarif_type', 'f_tarif_change_count', 'f_total_consumption_max', 'f_client_tenure_days', 'f_counter_statue_error_occured', 'f_index_diff_max', 'f_total_consumption_std', 'f_index_diff_std', 'disrict', 'consommation_level_2_max', 'consommation_level_3_mean', 'f_region_std_deviation_consumption_level_2', 'consommation_level_1_max', 'consommation_level_2_mean', 'f_region_std_deviation_consumption_level_3', 'consommation_level_2_std']

In [6]:
# 2. Liste der Spalten, die ignoriert werden sollen (z. B. ID-Spalten oder Kategorien)
ignore_cols = ['client_id', 'target']

# 3. Initialisiere das Objekt
finder = fraudfeaturefinder(df_feature=df_features, target_col='target', threshold=0.025, ignore_cols=ignore_cols, operations=["*", "/"], selected_features=top_n_features)

# 4. Suche nach guten Feature-Kombinationen
finder.find_good_combinations()

# 5. Ergebnisse speichern
finder.save_results("./data/mutual-info-combinations.csv")

numerber of feature pairs: 190
1 client_catg * remarque_frequency = 0.0300
1 client_catg / remarque_frequency = 0.0300
2 client_catg / f_counter_number_nunique = 0.0302
3 client_catg * avg_remarque_length = 0.0297
3 client_catg / avg_remarque_length = 0.0297
14 client_catg / consommation_level_3_mean = 0.0348
20 remarque_frequency * f_counter_number_nunique = 0.0265
20 remarque_frequency / f_counter_number_nunique = 0.0255
21 remarque_frequency / avg_remarque_length = 0.0285
32 remarque_frequency / consommation_level_3_mean = 0.0342
38 f_counter_number_nunique * avg_remarque_length = 0.0263
38 f_counter_number_nunique / avg_remarque_length = 0.0263
40 f_counter_number_nunique * f_tarif_change_count = 0.0312
40 f_counter_number_nunique / f_tarif_change_count = 0.0338
43 f_counter_number_nunique / f_counter_statue_error_occured = 0.0264
49 f_counter_number_nunique / consommation_level_3_mean = 0.0286
65 avg_remarque_length / consommation_level_3_mean = 0.0346

In [3]:
apply_saved_combinations(df_features, "./data/mutual-info-combinations.csv")

/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:113: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] / (df_feature[col2] + 0.1)
/Users/muri/education/spiced/WaterMLOps/ds-mlproject-fraud/fraudfeaturefinder.py:111: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_features[new_col_name] = df_feature[col1] * df_feature[col2]

,client_id,target,disrict,region,client_catg,f_invoive_date_diff_days,f_invoive_date_median_months,f_invoive_date_median_years,f_counter_statue_error_occured,f_counter_regions,...,f_autocombi_124,f_autocombi_125,f_autocombi_126,f_autocombi_127,f_autocombi_128,f_autocombi_129,f_autocombi_130,f_autocombi_131,f_autocombi_132,f_autocombi_133
0,train_Client_0,0.0,60,101,11,120.5,3.958607,0.329911,0,0,...,0.691762,202.523831,0.007936,0.000113,0.000113,4.733937e+05,0.001244,60.0,0.007936,4.733937e+05
1,train_Client_1,0.0,69,107,11,121.5,3.991459,0.332649,0,0,...,0.643013,61520.000000,0.009113,0.000163,0.000163,2.389087e+05,0.001788,69.0,0.009113,2.389087e+05
2,train_Client_10,0.0,62,301,11,147.0,4.829172,0.402464,0,0,...,5.785372,75.244511,0.003569,0.000083,0.000083,1.993463e+06,0.000909,62.0,0.003569,1.993463e+06
3,train_Client_100,0.0,69,105,11,121.0,3.975033,0.331280,0,0,...,0.018063,59200.000000,0.728477,0.000169,0.000169,5.410516e+01,0.001858,69.0,0.728477,5.410516e+01
4,train_Client_1000,0.0,62,303,11,124.0,4.073587,0.339493,0,0,...,4.162903,10.205953,0.004618,0.000586,0.000586,1.508963e+06,0.006444,62.0,0.004618,1.508963e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135488,train_Client_99995,0.0,62,304,11,113.0,3.712221,0.309377,1,0,...,0.000000,54480.000000,110.000000,0.000184,0.000184,0.000000e+00,0.002019,62.0,0.079080,0.000000e+00
135489,train_Client_99996,0.0,63,311,11,0.0,0.000000,0.000000,1,0,...,1.536692,491.157683,0.013235,0.000412,0.000412,1.689821e+05,0.004532,63.0,0.013235,1.689821e+05
135490,train_Client_99997,0.0,63,311,11,26.0,0.854139,0.071184,0,0,...,1.987899,29060.000000,0.010232,0.000344,0.000344,2.269577e+05,0.003785,63.0,0.010232,2.269577e+05
135491,train_Client_99998,0.0,60,101,11,122.0,4.007884,0.334018,0,0,...,0.267022,47.964900,0.020557,0.000228,0.000228,1.244614e+05,0.002511,60.0,0.020557,1.244614e+05
135492,train_Client_99999,0.0,60,101,11,122.0,4.007884,0.334018,0,0,...,0.300961,38720.000000,0.018239,0.000258,0.000258,1.078550e+05,0.002841,60.0,0.018239,1.078550e+05